"""初始化

Revision ID: 7a5dea059640
Revises: 
Create Date: 2021-06-06 15:00:54.570636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5dea059640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('img', sa.LargeBinary(length=2048), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('read_time', sa.Integer(), nullable=True),
    sa.Column('attitude', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Article')
    # ### end Alembic commands ###
